export const committeeMembers = [
  {
    id: 'member-001',
    name: 'Rajesh Kumar',
    role: 'Chairman',
    department: 'Executive Board',
    joinDate: '2010',
    clearance: 'DIVINE' as const,
    imageUrl: '/avatars/rajesh.jpg',
    bio: 'Visionary leader with 15 years of dedicated service to The Taj United Club.',
  },
  {
    id: 'member-002',
    name: 'Priya Sharma',
    role: 'Vice Chairperson',
    department: 'Executive Board',
    joinDate: '2012',
    clearance: 'DIVINE' as const,
    imageUrl: '/avatars/priya.jpg',
    bio: 'Strategic thinker driving membership excellence and member satisfaction.',
  },
  {
    id: 'member-003',
    name: 'Vikram Singh',
    role: 'Treasurer',
    department: 'Finance Division',
    joinDate: '2014',
    clearance: 'DIVINE' as const,
    imageUrl: '/avatars/vikram.jpg',
    bio: 'Financial steward ensuring sustainable growth and fiscal responsibility.',
  },
  {
    id: 'member-004',
    name: 'Aisha Patel',
    role: 'Events Director',
    department: 'Member Services',
    joinDate: '2015',
    clearance: 'MEMBER' as const,
    imageUrl: '/avatars/aisha.jpg',
    bio: 'Creative organizer crafting unforgettable experiences for our community.',
  },
  {
    id: 'member-005',
    name: 'Rohan Gupta',
    role: 'Facilities Manager',
    department: 'Operations',
    joinDate: '2016',
    clearance: 'MEMBER' as const,
    imageUrl: '/avatars/rohan.jpg',
    bio: 'Dedicated professional maintaining our world-class facilities.',
  },
  {
    id: 'member-006',
    name: 'Neha Desai',
    role: 'Membership Coordinator',
    department: 'Member Services',
    joinDate: '2018',
    clearance: 'MEMBER' as const,
    imageUrl: '/avatars/neha.jpg',
    bio: 'Welcoming new members and fostering a sense of belonging.',
  },
];

export const foodArchives = [
  {
    id: 'food-001',
    name: 'Royal Tandoori Delights',
    category: 'Indian',
    description: 'Authentic tandoori preparations with premium spices and traditional cooking methods.',
    speciality: 'Tandoori Chicken, Naan, Biryani',
    availableClearance: 'GUEST' as const,
    imageUrl: '/food/tandoori.jpg',
  },
  {
    id: 'food-002',
    name: 'Continental Elegance',
    category: 'Continental',
    description: 'Classic European cuisine crafted with precision and finest ingredients.',
    speciality: 'Pasta, Steaks, Seafood',
    availableClearance: 'MEMBER' as const,
    imageUrl: '/food/continental.jpg',
  },
  {
    id: 'food-003',
    name: 'Oriental Treasures',
    category: 'Asian',
    description: 'Exquisite Asian fusion celebrating flavors from across the continent.',
    speciality: 'Sushi, Dim Sum, Ramen',
    availableClearance: 'MEMBER' as const,
    imageUrl: '/food/oriental.jpg',
  },
  {
    id: 'food-004',
    name: 'The Royal Kitchen',
    category: 'Fine Dining',
    description: 'Exclusive tasting menus with curated wine pairings for the most discerning palate.',
    speciality: 'Chef\'s Tasting Menu, Rare Wines',
    availableClearance: 'DIVINE' as const,
    imageUrl: '/food/fine-dining.jpg',
  },
  {
    id: 'food-005',
    name: 'Cafe Serenity',
    category: 'Cafe',
    description: 'Casual dining with artisanal coffee and light fare for everyday enjoyment.',
    speciality: 'Coffee, Pastries, Salads',
    availableClearance: 'GUEST' as const,
    imageUrl: '/food/cafe.jpg',
  },
  {
    id: 'food-006',
    name: 'Spice Palace Bar',
    category: 'Bar & Lounge',
    description: 'Premium selection of spirits and cocktails in an elegant atmosphere.',
    speciality: 'Craft Cocktails, Premium Whiskey',
    availableClearance: 'MEMBER' as const,
    imageUrl: '/food/bar.jpg',
  },
];

export const facilities = [
  {
    id: 'fac-001',
    name: 'Olympic Swimming Pool',
    description: 'Olympic-sized pool with temperature control and professional coaching.',
    clearanceRequired: 'MEMBER' as const,
  },
  {
    id: 'fac-002',
    name: 'State-of-the-Art Gymnasium',
    description: 'Advanced fitness equipment with certified trainers.',
    clearanceRequired: 'MEMBER' as const,
  },
  {
    id: 'fac-003',
    name: 'Tennis & Squash Courts',
    description: 'Professional-grade courts with booking system.',
    clearanceRequired: 'MEMBER' as const,
  },
  {
    id: 'fac-004',
    name: 'Luxury Spa & Wellness',
    description: 'Premium spa services and wellness programs.',
    clearanceRequired: 'MEMBER' as const,
  },
  {
    id: 'fac-005',
    name: 'Golf Course',
    description: '18-hole championship golf course.',
    clearanceRequired: 'DIVINE' as const,
  },
  {
    id: 'fac-006',
    name: 'Library & Study Center',
    description: 'Extensive collection of books and research materials.',
    clearanceRequired: 'MEMBER' as const,
  },
];

export const events = [
  {
    id: 'event-001',
    title: 'Annual Gala Dinner',
    date: '2024-06-15',
    category: 'Formal Event',
    description: 'Grand celebration of excellence and community',
    clearanceRequired: 'MEMBER' as const,
  },
  {
    id: 'event-002',
    title: 'Summer Tournament',
    date: '2024-07-20',
    category: 'Sports',
    description: 'Inter-club championship matches',
    clearanceRequired: 'MEMBER' as const,
  },
  {
    id: 'event-003',
    title: 'Cultural Evening',
    date: '2024-08-10',
    category: 'Cultural',
    description: 'Celebration of arts and performances',
    clearanceRequired: 'MEMBER' as const,
  },
  {
    id: 'event-004',
    title: 'Exclusive Divine Retreat',
    date: '2024-09-05',
    category: 'Exclusive',
    description: 'Members-only exclusive gathering',
    clearanceRequired: 'DIVINE' as const,
  },
];

export const membershipPlans = [
  {
    id: 'plan-001',
    name: 'Standard Membership',
    monthlyFee: 500,
    annualFee: 5000,
    benefits: [
      'Access to main dining facilities',
      'Library access',
      'Member events attendance',
      'Discounted services',
    ],
    clearanceLevel: 'MEMBER' as const,
  },
  {
    id: 'plan-002',
    name: 'Premium Membership',
    monthlyFee: 1000,
    annualFee: 10000,
    benefits: [
      'All Standard benefits',
      'Spa & wellness services',
      'Priority event booking',
      'Guest privileges',
      'Concierge service',
    ],
    clearanceLevel: 'MEMBER' as const,
  },
  {
    id: 'plan-003',
    name: 'Divine Circle',
    monthlyFee: 2500,
    annualFee: 25000,
    benefits: [
      'All Premium benefits',
      'Exclusive golf course access',
      'Private dining rooms',
      'Personal concierge',
      'Investment committee membership',
      'VIP event access',
    ],
    clearanceLevel: 'DIVINE' as const,
  },
];
